### PR TITLE
Allow unix sockets to be used, fixes #151

### LINKED ISSUE #151: Support unix socket
It works fine when forcing the url into the code. However there is no API to arrive there, since all the parsing stuff will throw an error when using something like `unix:///var/run/program.sock`.

Will gladly do a PR but i don't know which approach should be better :

  * Allow parsing stuff to handle unix scheme ? (will be hard IMO and add a lot of code to reproduce behavior of some PHP functions)
  * Add an extra option, that allows to override the uri of a request (like a remote_socket_endpoint option), which is not parsed (find this better, but may not be the philosophy of this package)

### PR DESCRIPTION
**Pull request by kelunik**
We can probably add a `FixedSocketPool` or something like that to `amphp/socket`.

### CODE REVIEW

**Comment by joelwurtz** [comment]
👍 for the fixed socket pool but can be done later, patch to the local address is on the contrary mandatory for this.

Also forget you already told me about this, my bad :/

**Comment by kelunik** [comment]
@rdlowrey @bwoebi @trowski Opinions for the value to use here? I think `""` is reasonable.

**Comment by trowski** [comment]
Should this be fixed here or perhaps return "unix-socket" in amphp/socket?

**Comment by joelwurtz** [comment]
In this case the local adress is the same as the remote adress (both are the socket file) ?

**Comment by kelunik** [comment]
That sounds reasonable as well!

**Comment by kelunik** [comment]
Closing, as this will be fixed in `amphp/socket` instead.

**Pull request closed without merging**
