### PR TITLE
Update socket dependency

### PR DESCRIPTION
**Pull request by danog**
As usual, a release would be nice :)

### CODE REVIEW

**Comment by kelunik** [comment]
Why do you want to relax the version constraint?

**Comment by danog** [comment]
As you already saw on tg, I'm creating DNS over HTTPS client that requires artax and dns, but only the latest version of socket allows installing amphp/dns ^1, which is the version I'd like to use.
You told me to use amphp/http-client, instead: why is that, what is difference? Why is this repo being deprecated?

**Comment by kelunik** [comment]
Your commit doesn't change, which highest version can be installed, it just lowers the lower version.

**Comment by danog** [comment]
It doesn't automatically install amphp/dns 1.0 (that has to be done separately), but it removes the second subversion constraint, allowing clients to install v0.10.* of this lib instead of only v0.10.5; on my machine composer installs 0.10.12

**Comment by kelunik** [comment]
There's a caret at the beginning, allowing everything >=0.10.5, <0.11.0

**Comment by danog** [comment]
On pre-1.0 versions, the caret treats the first subversion (x.**y**.z) as if it defined breaking changes (**x**.y.z on 1+ versions): [0.10.12](https://semver.mwl.be/#?package=amphp%2Fsocket&version=%5E0.10.12&minimum-stability=stable), [0.10](https://semver.mwl.be/#?package=amphp%2Fsocket&version=%5E0.10&minimum-stability=stable)

**Pull request closed without merging**
