### PR TITLE
Enforce size limit also on gzipped streams

### PR DESCRIPTION
**Pull request by kelunik**
Might not be the prettiest implementation, but it works.

### CODE REVIEW

**Comment by bwoebi** [comment]
This is though only meaningful if the incoming data isn't specifically crafted to produce enormous amounts of data, right?

**Comment by kelunik** [comment]
Aborts just fine with https://blog.haschek.at/tools/bomb.php

**Comment by bwoebi** [comment]
Ah, yeah. Inflate only may decompress to a size maximally 1032 times larger than the input.
Given that we have a small chunk size of just 16 KB, we won't get more than 16 MB of inflated input.

So, yes, it should probably be enough.

**Comment by kelunik** [comment]
Merging and releasing a bugfix version then?

**Pull request merged**
